Scaffold-Stark/scaffold-stark-2

- packages/snfoundry/bash/run-devnet.sh
- packages/snfoundry/package.json
bash calls are simple inside `bash`. remove them to avoid confusion and directly set it on the `package.json`
> Remove bash

- packages/nextjs/components/ScaffoldStarkAppWithProviders.tsx
- packages/nextjs/contracts/deployedContracts.ts
- packages/nextjs/services/web3/provider.ts
> Eth devnet display

- packages/snfoundry/scripts_js/deploy.js
- packages/snfoundry/scripts_js/deploy_contract.js
> fix deploy scripts

- packages/nextjs/app/debug/_components/contract/ContractReadMethods.tsx
- packages/nextjs/app/debug/_components/contract/ContractVariables.tsx
- packages/nextjs/app/debug/_components/contract/ContractWriteMethods.tsx
- packages/nextjs/app/debug/_components/contract/utilsContract.tsx
- packages/nextjs/hooks/scaffold-stark/useScaffoldContractWrite.ts
- packages/nextjs/utils/scaffold-stark/contract.ts
> auto parsing on scaffold contracts

- packages/nextjs/hooks/scaffold-stark/useTransactor.tsx
> improve tx finality

- README.md
- packages/snfoundry/.env.example
> Update readme, clean files

- packages/snfoundry/contracts/src/challenge0.cairo
- packages/snfoundry/scripts_js/deploy.js
> Feat(Challenge 0): Implement Enumerable feature

- packages/snfoundry/contracts/src/challenge0.cairo
- packages/snfoundry/scripts_js/deploy.js
> Improve Challenge-0: Implement custom fn transfer_from

- packages/nextjs/components/scaffold-stark/CustomConnectButton/ConnectModal.tsx
- packages/nextjs/components/scaffold-stark/CustomConnectButton/Wallet.tsx
- packages/nextjs/hooks/scaffold-stark/useAutoConnect.ts
- packages/nextjs/services/web3/stark-burner/BurnerConnector.ts
- packages/nextjs/utils/devnetAccounts.ts
Fixes #77
Requires css to look better. Now when the user select burner wallet, all wallets available are displayed.
Just click one of them to select it.
> Burner wallets

- packages/nextjs/hooks/scaffold-stark/useScaffoldEthBalance.ts
Fixes [41](https://github.com/Quantum3-Labs/speedrunstark/issues/41)
> Fix: Remove padding during format of eth balance

- packages/nextjs/components/scaffold-stark/CustomConnectButton/ConnectModal.tsx
- packages/nextjs/components/scaffold-stark/CustomConnectButton/Wallet.tsx
> styles: Improve List

- packages/nextjs/app/debug/_components/DebugContracts.tsx
- packages/nextjs/app/debug/_components/contract/WriteOnlyFunctionForm.tsx
- packages/nextjs/hooks/scaffold-stark/useScaffoldMultiContractWrite.ts
- packages/nextjs/hooks/scaffold-stark/useSwitchNetwork.ts
- packages/nextjs/hooks/scaffold-stark/useTransactor.tsx
- packages/nextjs/package.json
- packages/nextjs/utils/scaffold-stark/contract.ts
- yarn.lock
Fixes #83
Support for multicall using `createContractCall`
> update: error message handling & multi write hook

- packages/nextjs/contracts/deployedContracts.ts
- packages/snfoundry/contracts/src/TestTypes.cairo
Add fn in SC `TestTypes.cairo` the Void, Bool, ByteArray
> Add new Types

- packages/nextjs/hooks/scaffold-stark/useScaffoldEthBalance.ts
- packages/nextjs/hooks/scaffold-stark/useScaffoldReadContract.ts
- packages/nextjs/hooks/scaffold-stark/useScaffoldWriteContract.ts
> Hook names

- packages/nextjs/app/page.tsx
> add connected address

- .github/workflows/lint.yml
- packages/nextjs/app/debug/_components/contract/ContractInput.tsx
- packages/nextjs/components/scaffold-stark/Input/IntegerInput.tsx
- packages/nextjs/components/scaffold-stark/Input/utils.ts
- packages/snfoundry/package.json
Fixes #139
- I have change the `format` script as well to format rust files as it was before as it's causing issues in the workflow
> Contract input

- packages/snfoundry/scripts-ts/deploy-contract.ts
> add options for maxFee on deploy

- README.md
- packages/snfoundry/.env.example
- packages/snfoundry/contracts/src/YourContract.cairo
- packages/snfoundry/contracts/src/test/TestContract.cairo
Clean files on contracts and tests
Add rpc -v 0.7
> Improve contracts and cairo test

- packages/nextjs/components/ScaffoldStarkAppWithProviders.tsx
democratization
irrelevant
this won't affect already-connected users,
but will only show a random order for new users
> chore: randomize wallets

- packages/nextjs/components/scaffold-stark/Faucet.tsx
- packages/nextjs/hooks/scaffold-stark/useDeployedContractInfo.ts
- packages/snfoundry/scripts-ts/deploy.ts
> feat: warning modal in devnet off

- .github/workflows/test_contract.yml
- README.md
- packages/nextjs/components/scaffold-stark/Input/AddressInput.tsx
- packages/nextjs/utils/scaffold-stark/contract.ts
- packages/snfoundry/contracts/Scarb.lock
- packages/snfoundry/contracts/Scarb.toml
- packages/snfoundry/contracts/src/YourContract.cairo
- Bump to snfoundry v0.25.0
- Update readme
> Minor changes

- packages/nextjs/hooks/useConditionalStarkProfile.tsx
> fix : vercel deploy

- packages/nextjs/components/ScaffoldStarkAppWithProviders.tsx
- packages/nextjs/services/web3/connectors.tsx
> Fix correctly display wallet connectors

- .github/workflows/release-create-stark.yaml
As tested in [test-origin](https://github.com/Quantum3-Labs/test-origin/actions/runs/9978606430/job/27575873214) repo
> workflow to update create-stark in every PR

- packages/nextjs/components/Header.tsx
- packages/snfoundry/scripts-ts/deploy-contract.ts
> update: wallet not deployed in ui & deploy.ts

- packages/nextjs/app/debug/_components/contract/ReadOnlyFunctionForm.tsx
- packages/nextjs/app/debug/_components/contract/utilsDisplay.tsx
- yarn.lock
- Input on fields that would parse into BigInt, (e.g. any u256 field)
- Click "Read"
- Should show "Do not know how to serialize BigInt"
- Do any operations what would display in numbers outside the max or min boundary for Javascrtip Number
- Should display number incorrectly with decimal places)
- Reference to why flatten to string: https://starknet-react.com/hooks/query/usecontractread
> fix: big int input and display bug

- .gitmodules
- packages/snfoundry/package.json
> chore : remove submodule

- packages/snfoundry/contracts/Scarb.toml
- packages/snfoundry/contracts/src/YourContract.cairo
- packages/snfoundry/contracts/src/test/TestContract.cairo
> Improve contract

- packages/nextjs/app/debug/_components/contract/DisplayVariable.tsx
- packages/nextjs/app/debug/_components/contract/ReadOnlyFunctionForm.tsx
- packages/nextjs/app/debug/_components/contract/WriteOnlyFunctionForm.tsx
- packages/nextjs/app/debug/_components/contract/utilsContract.tsx
- packages/nextjs/app/debug/_components/contract/utilsDisplay.tsx
- packages/nextjs/hooks/scaffold-stark/useScaffoldMultiWriteContract.ts
- packages/nextjs/hooks/scaffold-stark/useScaffoldReadContract.ts
- packages/nextjs/hooks/scaffold-stark/useScaffoldWriteContract.ts
- packages/nextjs/utils/scaffold-stark/common.ts
- packages/nextjs/utils/scaffold-stark/contract.ts
Fixes #216 
Hooks to pay attention to
- useReadContract
- useSendTransaction
> feat(v3): migration into v3 dependencies

- packages/nextjs/components/scaffold-stark/CustomConnectButton/AddressInfoDropdown.tsx
- packages/nextjs/components/scaffold-stark/CustomConnectButton/index.tsx
- packages/nextjs/hooks/scaffold-stark/useScaffoldReadContract.ts
- I faced issues using useContractRead hook, then I updated this way. Please check what do you think @metalboyrick @jrcarlos2000 
- Remove this files to avoid conflict during sync of scaffold-stark and speedrun/challenges
> Update useContractRead hook

- packages/nextjs/components/Header.tsx
Fixes #260 
FIxes https://github.com/Quantum3-Labs/speedrunstark/issues/111
> fix: do not show wallet not deployed in wrong network

- .github/workflows/main.yml
- README.md
- package.json
- packages/nextjs/hooks/scaffold-stark/__tests__/useDeployedContractInfo.test.ts
- packages/nextjs/hooks/scaffold-stark/__tests__/useOutsideClick.test.ts
- packages/nextjs/package.json
- packages/nextjs/vitest.config.ts
- yarn.lock
- Recommended coverage >= 70%
NOTE=
- `yarn test:nextjs` to run regular tests with watch mode
- `yarn test:nextjs run` to run regular tests without watch mode
- `yarn test:nextjs run --coverage` to run regular tests without watch mode with coverage
> test: configure and add sample unit tests

- packages/nextjs/hooks/scaffold-stark/__tests__/useAutoConnect.test.ts
test: useAutoConnect using vitest #294
> test: implement test for useAutoConnect.ts

- packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldMultiWriteContract.test.ts
- packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldWriteContract.test.ts
> test: create test for useScaffoldWriteContract hook

- packages/nextjs/app/debug/_components/contract/ContractReadMethods.tsx
As discussed, we have cleaned up unnecessary imports.
> Remove import unnecessary

- packages/snfoundry/scripts-ts/deploy-contract.ts
- packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts
> hotfix: remove console log

- packages/nextjs/hooks/scaffold-stark/useScaffoldMultiWriteContract.ts
- packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts
`useScaffoldMultiWriteContract` just in time parsing to solve populate issue
> fix: `useScaffoldMultiWriteContract` just in time parsing to solve populate issue

- packages/nextjs/components/scaffold-stark/CustomConnectButton/ConnectModal.tsx
- packages/nextjs/hooks/scaffold-stark/useAutoConnect.ts
- packages/nextjs/services/web3/connectors.tsx
- packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts
Reported app not reconnecting when it is supposed to be reconnected, fixed. Cause was incorrect local storage keys.
> fix: auto connect fix

- packages/nextjs/app/debug/_components/contract/__test__/utilsContract.test.tsx
- packages/nextjs/app/debug/_components/contract/utilsContract.tsx
- packages/nextjs/utils/scaffold-stark/types.ts
> add unit test for getArgsAsStringInputFromForm.

- packages/snfoundry/contracts/src/complex.cairo
- packages/snfoundry/contracts/src/events.cairo
- packages/snfoundry/contracts/src/lib.cairo
- packages/snfoundry/contracts/src/structs.cairo
- packages/snfoundry/contracts/src/tuples.cairo
- packages/snfoundry/contracts/src/vars.cairo
- packages/snfoundry/scripts-ts/deploy.ts
> feat: complex events

- packages/snfoundry/scripts-ts/deploy-contract.ts
- packages/snfoundry/scripts-ts/deploy.ts
> Avoid export contracts when reverted

- .husky/pre-commit
- CONTRIBUTING.md
- README.md
Removed unnecessary `local-devnet` references in `.husky` and fixed small syntax issues.
> Update small fixes

- packages/nextjs/hooks/scaffold-stark/useScaffoldMultiWriteContract.ts
> Support raw call useScaffoldMultiWriteContract 

- packages/nextjs/app/debug/_components/contract/utilsDisplay.tsx
- packages/nextjs/utils/scaffold-stark/contract.ts
Fixes #376
- [ x ] Enhancement
Tests was run and all passed!
> fix: converted somedata.toString(16) to feltToHex

- packages/nextjs/hooks/scaffold-stark/__tests__/useTransactor.test.ts
> test: useTransactor hook

- packages/nextjs/components/scaffold-stark/Address.tsx
- packages/nextjs/components/scaffold-stark/CustomConnectButton/AddressInfoDropdown.tsx
- packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldStarkProfile.test.ts
- packages/nextjs/hooks/scaffold-stark/useScaffoldStarkProfile.tsx
> tests: Add tests for useScaffoldStarkProfile

- packages/nextjs/next.config.mjs
- packages/nextjs/package.json
- yarn.lock
> Fix Vercel build & deployment issue

- packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldEventHistory.test.ts
- packages/nextjs/hooks/scaffold-stark/useScaffoldEventHistory.ts
- packages/nextjs/utils/Constants.ts
- packages/nextjs/utils/scaffold-stark/__test__/eventsData.test.ts
- packages/nextjs/utils/scaffold-stark/contract.ts
- packages/nextjs/utils/scaffold-stark/eventsData.ts
Almost all the event parameters have been parsed correctly. provide an option to format both the address type and the nested address type.
> format event data when needed

- packages/nextjs/app/debug/_components/contract/utilsContract.tsx
fixes dispatcher (or other imported structs) unable to read or write in debug UI
> fix: dispatcher error

- .devcontainer.json
- .github/workflows/main.yml
- .tool-versions
- README.md
- packages/snfoundry/contracts/Scarb.toml
- packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts
This PR integrates Docker using the **Starknet Foundation** image (`starknetfoundation/starknet-dev:2.9.2`) and updates **snfoundry** `0.35.1` to sync with the Docker environment.
- **Docker**: Adds Starknet Foundation image for streamlined development.
- **Snfoundry**: Updates to match Docker version.
- **No Breaking Changes**: No impact on syntax or other components.
- **Add README**: Optional information on installation with Docker.
> Dev Container Integration

- packages/nextjs/hooks/useScrollLock.ts
- packages/nextjs/utils/scaffold-stark/notification.tsx
Fixes #424 
- Added "View detail" button to expand and display full content
- Added "Close detail" button to collapse content back to default state
- Limited default content display to maximum 10 lines
- Automatically show "View detail" button when content exceeds 10 lines
- Disabled page scrolling when viewing content in expanded mode for better UX
- Optimized spacing and element alignment for different screen sizes
> Upgrade toast

- packages/nextjs/utils/scaffold-stark/__test__/types.test.ts
- packages/nextjs/utils/scaffold-stark/types.ts
> Option u256 is rendered as u256 in debug ui form

- packages/nextjs/.env.example
- packages/nextjs/services/web3/connectors.tsx
- packages/nextjs/supportedChains.ts
Currently we can not directly change devnet url and port by env, there are some hard code places.
> Support changing devnet default url

- packages/snfoundry/scripts-ts/deploy.ts
Fixes #441 
Updated deploy.ts:
- Replaced .then and .catch with async/await for better readability and maintainability.
- Enhanced Error Handling: Implemented try/catch blocks to better manage exceptions and ensure robust error reporting.
- Ensured that all deployment steps are executed in sequence.
This refactoring improves the overall structure and flow of the deployment script, making it more modern and easier to understand.
This is my first assigned issue and pull request in this project, and I'm excited to contribute. Thank you for your guidance and feedback! 😊
> [REFACTOR] Update deploy.ts and other files to async/await syntax #441

- packages/nextjs/scaffold.config.ts
- packages/nextjs/services/web3/connectors.tsx
[CHORE] Remove Kepler from Devnet Configuration
Fixes #440 
- **`walletConfig`**: Manages wallet behavior, including Kepler exclusion on Devnet.  
- **`excludeKeplerOnDevnet`**: Set to `true` to hide Kepler when using Devnet.  
- Ensure the frontend checks `scaffoldConfig.walletConfig.excludeKeplerOnDevnet` to exclude Kepler accordingly.
> [CHORE] Remove Kepler from Devnet Configuration

- .devcontainer.json
Version:
Scarb: 2.9.4
Starknet-foundry: 0.38.2
Starknet Devnet: 0.2.4
> Update devcontainer 2.9.4

- packages/nextjs/app/debug/_components/contract/__test__/utilsContract.test.tsx
- packages/nextjs/app/debug/_components/contract/utilsContract.tsx
- packages/nextjs/app/debug/_components/contract/utilsDisplay.tsx
- packages/nextjs/utils/scaffold-stark/types.ts
Bug: Scaffold Stark UI Incorrectly Displays Span Values #459
Bug: Scaffold Stark UI Incorrectly Displays Span Values #459
> fix:Scaffold Stark UI Incorrectly Displays Span Values

- .tool-versions
- packages/nextjs/app/debug/_components/contract/DisplayVariable.tsx
- packages/nextjs/app/layout.tsx
- packages/nextjs/contracts/deployedContracts.ts
- packages/nextjs/hooks/scaffold-stark/useTransactor.tsx
- packages/nextjs/package.json
- packages/snfoundry/contracts/src/YourContract.cairo
- packages/snfoundry/package.json
- packages/snfoundry/scripts-ts/deploy-contract.ts
- yarn.lock
fix:nextjs error and predeployed ETH STRK name() symbol() not working workaround
The Bravvos and Argent wallet still not working when deploying contract to sepolia
> Gian/update - fix:nextjs error and predeployed ETH STRK name() symbol() not working workaround

- packages/snfoundry/scripts-ts/deploy-contract.ts
- packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts
> Fix conflict flag deploy --no-reset

- packages/snfoundry/contracts/src/YourContract.cairo
- packages/snfoundry/contracts/tests/TestContract.cairo
Replace deposit of `eth` with `strk` on sample contract
> Update sample contract

- .github/workflows/release-create-stark.yaml
Update rysinc command to create-stark repo
> Update release of create stark

- .gitignore
- packages/snfoundry/contracts/Scarb.toml
> Clean files

- packages/snfoundry/contracts/Scarb.toml
> Add comment

- .github/workflows/release-create-stark.yaml
> Update create-stark release file

- packages/snfoundry/.env.example
> Revert last changes

- packages/snfoundry/.env.example
> Fix: Update .env.example file

- .github/workflows/release-create-stark.yaml
- Try to include .github/workflows/main.yml for create-stark
> Fix: try to include .github/workflows/main.yml for create-stark

- packages/snfoundry/contracts/Scarb.toml
> Chore: Update docs

- .github/workflows/release-create-stark.yaml
- packages/snfoundry/contracts/Scarb.toml
Remove comments from yaml file
> Remove comments from yaml file

- .husky/pre-commit
- Auto format when dev commit a message
> chore: pre-commit run format before check

- .github/workflows/e2e-test.yaml
- ui-automation/start.sh
- ui-automation/tests/argentx-wallet-interaction.spec.ts
- ui-automation/tests/pages/StrkDebugPage.ts
- The e2e test will now run if there's a new commit pushed to ```v3-bulletproof-contracts branch```
- This combine with the workflow in PR: ```https://github.com/Scaffold-Stark/scaffold-stark-2/pull/514``` will always make sure ```v3-bulletproof-contracts branch``` up to date for testing
> Fix workflow in bulletproof contracts

- .github/workflows/sync-bulletproof-contracts.yaml
This PR merges the latest changes from main into the v3-bulletproof-contracts branch to ensure that end-to-end tests are always run against the most up-to-date codebase.
Why this matters:
•	v3-bulletproof-contracts contains the full E2E test suite and test UI
•	Keeping it in sync with main ensures comprehensive test coverage
> chore: create v3 bulletproof contracts sync workflow

- .devcontainer.json
> chore: Bump SN Docker image version

- packages/nextjs/.env.example
- packages/nextjs/supportedChains.ts
> Fix: Update devnet rpc url

- .github/workflows/sync-speedrun-repo.yaml
> Update sync-challenges workflow

- .github/workflows/sync-speedrun-repo.yaml
Fix: Update commit message on sync speedrun workflow
> Fix: Update sync speedrun workflow

- packages/nextjs/app/debug/_components/contract/ContractInput.tsx
- packages/nextjs/app/debug/_components/contract/utilsContract.tsx
- packages/nextjs/utils/scaffold-stark/__test__/types.test.ts
> chore: fixed bug for untyped enum

- packages/nextjs/components/scaffold-stark/Faucet.tsx
- packages/nextjs/contracts/deployedContracts.ts
> fix: local faucet styling

- packages/snfoundry/scripts-ts/deploy-contract.ts
- packages/snfoundry/scripts-ts/deploy.ts
Fixes #570
- Signing and verifying typed data would confirm the private key matches the smart contract account, but that’s probably overkill for this case.
The error message in terminal
> feat(snfoundry): assert deployer is defined + improve error message

- .tool-versions
- README.md
- package.json
- packages/snfoundry/contracts/Scarb.lock
- packages/snfoundry/contracts/Scarb.toml
This PR comprehensively updates the project's core dependencies and configuration files to align with the latest stable releases across the Starknet ecosystem. The goal is to improve compatibility, ensure forward compatibility with newer tools, and reduce technical debt across both contract and testing environments.
closes #578
**What Was Updated**
Cairo Dependencies (Scarb.toml)
OpenZeppelin
openzeppelin_access  from 1.0.0 -> '2.0.0`
openzeppelin_token from 1.0.0 -> '2.0.0`
openzeppelin_utils from 1.0.0 -> '2.0.0`
Upgraded openzeppelin_testing from 4.1.0 → 4.2.0
SNFoundry
Upgraded snforge_std from 0.44.0 → 0.45.0
Updated to 0.4.3
**Tooling**
.tool-versions was updated to reflect the latest versions of:
**starknet-devnet**
snfoundry
Other project-specific CLI tools as applicable
README.md …
> chore: contracts toolkit dependency updates

- .github/workflows/demo.yaml
Fixes #574
- Pre-deploy the contract on Sepolia first.
- If a developer deploys the contract again, it will overwrite the default config in the `deployedContracts.ts` file 🛠️
> ci: deploy YourContract when deploy DemoApp

- packages/nextjs/supportedChains.ts
Fixes  #517 
Tested and updated `mainnetFork` chain configuration to latest settings
> chore: update fork information

- README.md
Update README to latest version
> docs: update readme to current conditions of repo

- README.md
Chery pick to update README on main
> fix(hotfix): update documentation for latest version in main

- README.md
- package.json
Reconcile hotfix es from main to develop
> chore: reconcile main [skip ci]

- package.json
Revert unintentional version bump
> hotfix: revert bump

- .tool-versions
- README.md
- packages/snfoundry/contracts/Scarb.lock
- packages/snfoundry/contracts/Scarb.toml
- packages/snfoundry/package.json
- yarn.lock
> feat: update deps on devtooling

- .cursorrules
- .github/copilot-instructions.md
- global_rules.md
> feat: cursorrules and other LLM rules.

- .github/workflows/sync-bulletproof-contracts.yaml
> build: sync develop with bulletproof contracts branch workflow

- .github/workflows/demo.yaml
Fixes Missing YourContract on Demo Page
> chore: update deploy to demo workflow

- packages/snfoundry/contracts/src/YourContract.cairo
> fix: your contract set_greeting not updating premium(SS2-135)

- .github/workflows/release-create-stark.yaml
- package.json
- packages/nextjs/package.json
- packages/snfoundry/package.json
- yarn.lock
Updated NPM dependencies in lieu of the recent attacks, please wait for merging until other repository issues are resolved
> hotfix: npm dependency update on chalk

- packages/snfoundry/scripts-ts/deploy-contract.ts
- packages/snfoundry/scripts-ts/deploy.ts
- packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts
- Improved error messages for class declaration and deployment execution failures, providing clearer feedback on issues such as insufficient balance, RPC connection errors, and timeouts.
- Updated logging to show detailed error messages when exceptions occur during deployment processes.
- Ensured consistent error handling across deployment-related functions for better debugging and user experience.
- Added estimation tip for contract declaration
- Added estimation retry interval for contract declaration
> chore: Simplify error messages and refactor contract declaration
