Scaffold-Stark/scaffold-stark-2

packages/nextjs/app/debug/_components/contract/DisplayVariable.tsx
packages/nextjs/app/debug/_components/contract/ReadOnlyFunctionForm.tsx
packages/nextjs/hooks/scaffold-stark/useAutoConnect.ts

Fixes #47
We have to treat `useContractRead` as a fetch function, every time `form` was changing made args to change, executing the hook several times.
I fixed by changing another state `inputValue` when was needed (inside the onClick) to prevent this behavior.

contract variables called on every render. 

---

README.md

Fix typo on readme 
- Remove inexistant documentation link 
- Fix typo for coming soon. 
- Fix typo for aniway to anyway. 
- Add documentation and website links 
- Change js to ts scripts for paths. 
Closes #138

[Readme] fix errors  

---

.github/workflows/demo.yaml

Workflows / vercel deployment / version control
The final outcome is to have a sample website out of scaffold-stark repo. There are some ways this can be done, we can just add one more workflow to it. This is a simpler approach. 
Or we can have a public repository called scaffol-stark-demo, that is like a website sample out of Scaffold-stark.
Everytime there is an update on the main repo, the workflow should update another scaffol-stark-demo repo and run a workflow on it to deploy it to vercel. 
I choose use env to control the deployed block chain network. It might lead to a bit unmaintainable.
every time we push code to `nextjs` folder on the master branch, it would trigger this pipeline to deploy a new nextjs app on vercel. (using sepolia net)

devops(demo): support scaffol-stark-demo workflow

---

packages/nextjs/components/Header.tsx

Small syntax change in the status to detect the wallet connection before showing the button

Fix botton Wallet Not Deployed

---

packages/nextjs/app/debug/_components/contract/ReadOnlyFunctionForm.tsx

Fixes #244 
- Also optimized the callback `handleRead` with the `useCallback` hook

fix: clicking twice to open read

---

packages/nextjs/hooks/scaffold-stark/useScaffoldContract.ts

Fixes #243 
- Added relevant TODOs for future tech debts
- Might need to incorporate own parser to emulate `parseResponse = true` behaviour

fix: inconsistent behaviour of usescaffoldcontract

---

packages/nextjs/services/web3/connectors.tsx

Fixes #256 
Fixes https://github.com/Quantum3-Labs/speedrunstark/issues/110
- Note this is  a workaround that tampers with the `disconnect()` function of the connector. I've injected a local storage removal operation to clear local storage so that `useAutoConnect()` does not go in a infinite loop when it finds something stored.
- Should be able to resolve the issue in speedrunstark (https://github.com/Quantum3-Labs/speedrunstark/issues/110) as well @gianalarcon

fix: add workaround on wallet connectors to remove from localStorage

---

packages/nextjs/app/debug/_components/contract/ContractUI.tsx

Fixes https://github.com/Scaffold-Stark/scaffold-stark-2/issues/281
Replaced the separate `Read` and `Write` sections with a single tabbed interface using [DaisyUI's](https://daisyui.com/components/tab/) tabs.
Also, as suggested in the issue made use of [next/dynamic](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading) to lazy load the content of the `Write` tab
NOTE for reviewers: As mentioned in the telegram channel there are many styles for the tabs. On this PR I added 4 different commits with 4 different proposals. Here is what each of them looks like, please let me know which one you like the most to either remove the other commits or just apply the change of the option you like the most. And also, if you have another proposal please let me know

feat: Add tabs to display Read and Write methods in Debug Contracts page

---

package.json
packages/snfoundry/package.json
packages/snfoundry/scripts-ts/verify-contracts.ts

Fixes #288 
A new command is added that allows verifying the deployed contract from the `deployedContracts.ts` file on Walnut.dev.  The following parameter must be included:
--network: sepolia or mainnet
For example:
`yarn verify --network sepolia`

feat: Add verification contract command

---

packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldContract.test.ts
packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldReadContract.test.ts

This pull request introduces unit tests for the useScaffoldContract and useScaffoldReadContract hooks, ensuring they behave as expected in various scenarios. These tests cover:
- Correct behavior of the hooks under normal conditions.
- Ensuring useReadContract is called with the correct parameters.
- Ensuring that read is disabled when arguments contain undefined.
- Ensuring that read is enabled when arguments do not contain undefined.
- Passing block Identifier as pending (the default)
- Ensuring a contract is returned when deployedContractData is available.
- Ensuring that undefined contract is returned when deployedContractData is not available.
- Ensuring that RpcProvider is created with the correct public URL.
- Ensuring that isLoading is set to true when deployed contract is …

Test: Add unit test for useScaffoldContract and useScaffoldReadContract

---

packages/nextjs/components/scaffold-stark/CustomConnectButton/ConnectModal.tsx
packages/nextjs/hooks/scaffold-stark/useAutoConnect.ts
packages/nextjs/scaffold.config.ts
packages/nextjs/utils/Constants.ts

feat: set autoConnet() expiry time

---

package.json
packages/snfoundry/package.json
packages/snfoundry/scripts-ts/deploy-contract.ts
packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts

- Integrated and modified `yarn deploy` now always resets contracts.
- Integration of `yarn deploy --noreset`, this new command does not reset previous deployments.
Fixes #285

Add yarn deploy --noreset and modify yarn deploy

---

packages/nextjs/hooks/scaffold-stark/useScaffoldWriteContract.ts

Issue where a wrong variable `newArgs` was incorrectly used in `useScaffoldWriteContract.

fix: wrong variables in scaffold write contract

---

packages/nextjs/hooks/scaffold-stark/useScaffoldReadContract.ts
packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts

In speedrun, there is the issue of "Cannot mint token of same id". This is caused by `useReadContract` not working properly if args is not defined. Fixed by adding a fallback `[]` if args is undefined

fix: use read contract watch mode does not work

---

packages/nextjs/utils/scaffold-stark/contract.ts

In the contract.ts file in the `decodeParamWithType` we have returned to the simpler version by removing `getChecksumAddress` and adding `validateAndParseAddress`.
Example Speedrun CH-0

Solution in event issue

---

packages/nextjs/hooks/useConditionalStarkProfile.tsx
packages/nextjs/scaffold.config.ts
packages/nextjs/supportedChains.ts

Fixes #313 
If developer start the local testnet from a mainnet fork chain, something like `starknet-devnet --fork-network https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_7/PLACE_HOLDER --seed 0 --account-class cairo1`, then can change `targetNetworks` to `[forkMainnet]`

add a new chain type only for forked mainnet

---

packages/snfoundry/contracts/src/arrays_spans.cairo
packages/snfoundry/contracts/src/complex.cairo
packages/snfoundry/contracts/src/structs.cairo

fix: enum need default value if stored as storage

---

packages/snfoundry/scripts-ts/deploy-contract.ts

I realized sometimes there will be this pattern:
`../contracts/target/dev/contracts_contracts_${contract}_${contract}.compiled_contract_class.json`
and not:
`../contracts/target/dev/contracts_${contract}.compiled_contract_class.json`
this finding solution works in a better way by finding the file matching it with its tail.

fix : handle edge case for deployed contracts

---

packages/nextjs/components/scaffold-stark/Address.tsx

Added a placeholder if wallet not connected

---

packages/nextjs/utils/scaffold-stark/__test__/common.test.ts

Fixes #372 
- Test
- Test coverage

write test for utils/scaffold-stark/common.ts

---

packages/nextjs/utils/scaffold-stark/__test__/types.test.ts

- Fixes #371
Added comprehensive unit tests for utils/scaffold-stark/types.ts file with:

feat: add unit test for types.ts

---

packages/nextjs/components/scaffold-stark/CustomConnectButton/index.tsx
packages/nextjs/scaffold.config.ts
packages/nextjs/supportedChains.ts

Removes `isFork` flag due to redundancy with definition of `mainnetFork`

chore: remove `isFork` flag from `scaffold.config.ts`

---

packages/nextjs/services/web3/provider.ts

Modified RPC provider selection logic due to Sepolia testnet and devnet sharing the same chain ID `0x534e5f5345504f4c4941`. Previously, this caused the provider to incorrectly fallback to public endpoints even when custom RPC was configured.
Changed `containsDevnet` check to properly handle network identification:
```diff
- return networks.filter((it) => it.id == chains.devnet.id).length > 0;
+ return networks.filter((it) => it.network == chains.devnet.network).length > 0;

fix: devnet matches sepolia

---

packages/nextjs/app/debug/_components/contract/TxReceipt.tsx
packages/nextjs/utils/scaffold-stark/contract.ts

chore: fix some typos in comment

---

packages/nextjs/hooks/scaffold-stark/useScaffoldEventHistory.ts
packages/nextjs/utils/scaffold-stark/__test__/eventKeyFilter.test.ts
packages/nextjs/utils/scaffold-stark/__test__/mockDeployedContractAbi.ts
packages/nextjs/utils/scaffold-stark/contract.ts
packages/nextjs/utils/scaffold-stark/eventKeyFilter.ts

Support event filter
doc pull request: https://github.com/Scaffold-Stark/ss2-docs/pull/88
Reference the implementation of `starknet_getEvents` endpoint in `starknet-devnet-rs`, filter logic is in `crates/starknet-devnet-core/src/starknet/events.rs`
```
/// This method checks if the keys apply to the keys_filter and returns true or false
///
/// # Arguments
/// * `keys_filter` - Optional. The values to filter the keys by.
/// * `keys` - The keys to check if they apply to the filter.
fn check_if_filter_applies_for_event_keys<T>(keys_filter: &Option<Vec<Vec<T>>>, keys: &[T]) -> bool
where
T: PartialEq + Eq,
{
match &keys_filter {
Some(keys_filter) => {
for (event_key, accepted_keys) in keys.iter().zip(keys_filter) {
if !accepted_keys.is_empty() && !accepted_keys.contains(event_key) {
return …
```

Event key filter

---

packages/nextjs/components/scaffold-stark/Input/AddressInput.tsx
packages/snfoundry/scripts-ts/helpers/deploy-wrapper.ts

Fixes #420
Changes made:
1. Updated the regex to `/^0x[a-f0-9]{1,64}$/` which:
- Matches `0x` prefix
- Followed by 1-64 hex characters (a-f, 0-9)
- No need for capture groups or additional checks
2. Removed the redundant length check since it's handled by the regex
3. Removed the redundant double-0x check since the regex ensures only one 0x at the start
4. Fixed formatting issues in `deploy-wrapper.ts`
The validation is now more appropriate for Starknet addresses while being simpler and more maintainable.

fix: correct address regex in AddressInput

---

README.md

This PR corrects the version mismatch in the documentation for Starknet Foundry. The required version is updated to 0.35.1, aligning with the compatible versions section to avoid user confusion.

chore(docs): fix incorrect Starknet Foundry version in documentation

---

packages/nextjs/hooks/scaffold-stark/ContractClassHashCache.ts
packages/nextjs/hooks/scaffold-stark/__tests__/ContractClassHashCache.test.ts
packages/nextjs/hooks/scaffold-stark/__tests__/useDeployedContractInfo.test.ts
packages/nextjs/hooks/scaffold-stark/useDeployedContractInfo.ts

We use `useDeployedContractInfo` in many places, then the `getClassHashAt` API is triggered significantly more times than actually needed. When we provide provider url in env file, it will cause http 429 error.
In this PR, added a singleton instance to handle the cache,  it will reuse the api call as well.

Cache getClassHash request and result

---

package.json
packages/nextjs/next.config.mjs
packages/snfoundry/scripts-ts/deploy.ts
yarn.lock

Fixes #367
- Silenced verbose logs from **Workbox** by setting `debug: false` in `next.config.mjs`.
- Reduced unnecessary **Webpack** logs by setting `infrastructureLogging.level` to `error`.
- Applied changes in `packages/nextjs/next.config.mjs`.
- Verified changes in production mode (`yarn build && yarn start`) to ensure logs are minimized.
- These changes enhance the developer experience by reducing noise in the console.

chore: silence Workbox and Webpack logs in console

---

.github/workflows/main.yml
.github/workflows/sync-basecamp-repo.yaml
.tool-versions
README.md
packages/nextjs/scaffold.config.ts
packages/snfoundry/contracts/Scarb.lock
packages/snfoundry/contracts/Scarb.toml
packages/snfoundry/contracts/src/YourContract.cairo
packages/snfoundry/scripts-ts/deploy.ts
yarn.lock

- Updated GitHub workflow configuration to automatically adapt to new dependency versions.
- Successfully performed comprehensive script testing and manual verification
- Maintained/kept starknet-devnet 2.3.0 version to prevent warning messages
- This PR serves as prerequisite work for issue #442
- Before merging, the docker container needs to be updated with the latest dependency versions to ensure full compatibility.

snfoundry: Update dependencies

---

packages/nextjs/.env.example

I found that in the `.env.example` file, under the new **[RPC-centralized](https://github.com/Scaffold-Stark/scaffold-stark-2/issues/445)** configuration, the UI was not displaying values correctly. This was due to an incorrect configuration of values in the `.env.local` or `.env` files. 
**Updated `.env.example` configuration:**
- Corrected and standardized the format of the RPC URLs for **Sepolia**, **Mainnet**, and **Devnet**.
- The environment variables are now correctly applied and formatted to ensure the UI displays values properly.

Fixed .env.example

---

packages/nextjs/services/web3/provider.ts

- Add warn for empty RPC Provider URL config in next .env

refactor: add warn for empty RPC Provider URL config in next .env

---

packages/nextjs/app/debug/_components/contract/WriteOnlyFunctionForm.tsx
packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldMultiWriteContract.test.ts
packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldWriteContract.test.ts
packages/nextjs/hooks/scaffold-stark/__tests__/useTransactor.test.ts
packages/nextjs/hooks/scaffold-stark/useScaffoldMultiWriteContract.ts
packages/nextjs/hooks/scaffold-stark/useScaffoldWriteContract.ts
packages/nextjs/hooks/scaffold-stark/useTransactor.tsx

Fixes #493
- Reload states after transaction is complete
- Correct notification flow
**useTransactor behavior:**
- Center sending transaction logic into this hook, no need to create other `useSendTransaction` and `useTransactionReceip`t hooks seperately
- Automatically handle transaction status and push correct notification
- return `writeTransaction`, `transactionReceiptInstance`, `sendTransactionInstance` instead of only writeTransaction
**writeTransaction behavior:**
- `writeTransaction` now only accept Call[] parameter
- `writeTransaction` can take optional parameter `withSendTransaction = false` to use manually send transaction with fallback, otherwise it will use sendTransaction hook as default

Fix: Fast Reload not working on testnet mode

---

packages/nextjs/hooks/scaffold-stark/useScaffoldEventHistory.ts
packages/nextjs/hooks/scaffold-stark/useScaffoldMultiWriteContract.ts
packages/nextjs/hooks/scaffold-stark/useScaffoldWriteContract.ts

Fixes [#218](https://github.com/Scaffold-Stark/speedrunstark/issues/218)
- do not read event if not enabled
- wait for contract to be deplpoyed, then throw error if deployedContractData not found
- proper isLoading state

Fixed the Hook useScaffoldEventHistory shows contract not found issue

---

packages/snfoundry/.env.example

The URL regarding deploying contracts was outdated (giving 503)

Fixes docs URL on .env.example

---

README.md

Recently I have discovered that simply running `asdf install` will give you all the needed dependencies. I believe this could help with the dependency installation. Please verify, thanks !

docs: update readme to use asdf install

---

packages/nextjs/app/debug/_components/contract/__test__/utilsContract.test.tsx
packages/nextjs/app/debug/_components/contract/utilsContract.tsx

Fix wrong tests which causes CI fails, when value is not selected, it is encoded as `undefined`, but in the tests previously it is encoded as empty strings, fixed by simulation unselected variants with `undefined`

test: fix enum parser tests

---

packages/nextjs/hooks/scaffold-stark/__tests__/useScaffoldEventHistory.test.ts
packages/nextjs/hooks/scaffold-stark/useScaffoldEventHistory.ts
packages/nextjs/utils/scaffold-stark/contract.ts

Fixes #543 
I constructed a new type to interact with another type, and extract the base name of the argument type it is given, so that 'Transfer' can be extracted from the long event name for instance, and the auto-complete still recognizes it. I changed this type in the UseScaffoldEventHistoryConfig (more like added, with an or separator so that both methods can be used). Then in the readEvents function, I made sure to check either the basename or the full name of the events for matching with the eventName argument.
Details in code, it was a very small change

Fix: Shortened Event Argument Names in useScaffoldEventHistory Hook

---

packages/nextjs/app/debug/_components/contract/ReadOnlyFunctionForm.tsx
packages/nextjs/utils/scaffold-stark/__test__/common.test.ts
packages/nextjs/utils/scaffold-stark/common.ts

Fixes [error when navigating to Debug Contracts (Challenge 1 & 2) ](https://github.com/Scaffold-Stark/speedrunstark/issues/249)
- Fixed `useReadContract` hook so it's only triggered when valid parameters are passed.
- Added a utility (`isValidContractArgs`) to validate contract read arguments before triggering the hook.
The issue occurred because `useReadContract` was being called with empty or invalid argument arrays, which caused the underlying contract ABI validation to throw:  
`Invalid number of arguments, expected N arguments, but got 0`.
This is now prevented by validating the input array length and content before passing it to the hook.

fix: error when navigating to Debug Contracts (Challenge 1 & 2) 

---

.github/workflows/main.yml
packages/nextjs/package.json

To prevent CI errors in Forks (in particular speedrun repositories), we designate `vitest` to pass if there are no test suites defined

chore: make vitest pass with no tests

---

packages/nextjs/contracts/predeployedContracts.ts
packages/nextjs/utils/Constants.ts

Some issues occurred on PR #593 where it is caused by wrong ABI, this PR should remove the bug. We have been using the wrong ABI for STRK contract since STRK contract is not exactly implemented in the OZ ERC20 method.
Credits to Phil26 from the Starknet.js team to help resolve this.

fix: use latest STRK ABI to ensure no `BigInt` conversion error on `parseEvent`

---

.tool-versions
README.md
package.json
packages/snfoundry/contracts/Scarb.lock
packages/snfoundry/contracts/Scarb.toml

- Fixed dependency conflict: Updated `openzeppelin_testing` from `4.2.0` to `4.3.0` in `Scarb.toml`
- Updated compatible versions: Changed Snforge version from `v0.45.0` to `v0.46.0` in `README`
- Updated Starknet Foundry installation instructions: Changed all references from `0.45.0` to `0.46.0`
- Verified build success: Confirmed that scarb build now works without version conflicts
- Updated documentation consistency: All version references now align with current project requirements
Fixes #606 
Related PR [#61 Scaffold site](https://github.com/Scaffold-Stark/scaffoldstark-site/pull/61)

chore(deps): Update Starknet Foundry to 0.46.0

---

packages/nextjs/hooks/scaffold-stark/useTransactor.tsx

Fixes intermittent error of `useTransactor` not picking up successful transactions in sepolia
Before - Inconsistent time and hints of hook not picking up transaction, the three transactions are similar
After - Consistent transaction times for similar transactions

fix: watch true on use transaction receipt
